---
- name: Monitor CPU, Memory, and Disk Usage
  hosts: all
  become: yes
  gather_facts: no

  vars:
    cpu_threshold: 80        # %
    memory_threshold: 80     # %
    disk_threshold: 80       # %

  tasks:

    ######################
    # CPU MONITORING
    ######################

    - name: Get CPU usage
      shell: |
        top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}'
      register: cpu_usage
      changed_when: false

    - name: Set CPU usage fact
      set_fact:
        cpu_used: "{{ cpu_usage.stdout | float }}"

    - name: Fail if CPU usage is high
      fail:
        msg: "CPU usage high: {{ cpu_used }}% (Threshold: {{ cpu_threshold }}%)"
      when: cpu_used > cpu_threshold


    ######################
    # MEMORY MONITORING
    ######################

    - name: Get memory usage
      shell: |
        free | awk '/Mem:/ { printf("%.2f"), $3/$2 * 100 }'
      register: memory_usage
      changed_when: false

    - name: Set memory usage fact
      set_fact:
        memory_used: "{{ memory_usage.stdout | float }}"

    - name: Fail if memory usage is high
      fail:
        msg: "Memory usage high: {{ memory_used }}% (Threshold: {{ memory_threshold }}%)"
      when: memory_used > memory_threshold


    ######################
    # DISK MONITORING
    ######################

    - name: Get disk usage
      shell: |
        df -h --output=pcent,target -x tmpfs -x devtmpfs | tail -n +2
      register: disk_usage
      changed_when: false

    - name: Check disk usage thresholds
      fail:
        msg: "Disk usage high on {{ item.split()[1] }}: {{ item.split()[0] }} (Threshold: {{ disk_threshold }}%)"
      loop: "{{ disk_usage.stdout_lines }}"
      when: item.split()[0].replace('%','') | int > disk_threshold

