---
- name: AWX-safe node resource monitoring
  hosts: all
  become: yes
  gather_facts: no

  vars:
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 80
    k3s_storage_threshold_gb: 10

- name: Mark controller & prepare reporting
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Mark this playbook run as coming from controller
      ansible.builtin.set_fact:
        monitoring_controller: true
      run_once: true

- name: Collect resource metrics on all nodes
  hosts: all
  become: yes
  gather_facts: no
  tasks:

    - name: Get CPU usage (100 - idle)
      ansible.builtin.shell: >
        top -bn1 | grep -i "cpu(s)" | awk '{print 100 - $8}'
      register: cpu_raw
      changed_when: false
      check_mode: no

    - name: Set CPU facts
      ansible.builtin.set_fact:
        cpu_used: "{{ cpu_raw.stdout | float | round(1) }}"
        cpu_fail: "{{ (cpu_raw.stdout | float) > cpu_threshold }}"

    - name: Get memory usage %
      ansible.builtin.shell: >
        free | awk '/^Mem:/ {printf "%.1f", ($3/$2)*100}'
      register: mem_raw
      changed_when: false
      check_mode: no

    - name: Set memory facts
      ansible.builtin.set_fact:
        memory_used: "{{ mem_raw.stdout | float }}"
        memory_fail: "{{ mem_raw.stdout | float > memory_threshold }}"

    - name: Get all filesystem usage percentages
      ansible.builtin.shell: >
        df -hP | awk 'NR>1 && $NF !~ /^\/dev\/loop/ && $NF !~ /^tmpfs/ {print $6 " " $5}'
      register: fs_raw
      changed_when: false
      check_mode: no

    - name: Find maximum disk usage percentage
      ansible.builtin.set_fact:
        disk_used_max: "{{ fs_raw.stdout_lines | map('split') | map('last') | map('regex_replace','%','') | map('int') | max | default(0) }}"
        disk_fail: "{{ (fs_raw.stdout_lines | map('split') | map('last') | map('regex_replace','%','') | map('int') | max | default(0)) > disk_threshold }}"

    - name: Store filesystem list for detailed report
      ansible.builtin.set_fact:
        filesystems: >
          {{ fs_raw.stdout_lines
             | map('split', None, 1)
             | map('community.general.dict', keys=['mount','usage'])
          }}

    - name: Get k3s containerd storage usage (GB)
      ansible.builtin.shell: >
        du -sx --block-size=1G /var/lib/rancher/k3s/agent/containerd 2>/dev/null | awk '{print $1}' || echo 0
      register: k3s_raw
      changed_when: false
      check_mode: no
      ignore_errors: yes   # directory might not exist

    - name: Set k3s storage facts
      ansible.builtin.set_fact:
        k3s_storage_gb: "{{ k3s_raw.stdout | int }}"
        k3s_fail: "{{ (k3s_raw.stdout | int) > k3s_storage_threshold_gb }}"

    - name: Create per-host summary fact
      ansible.builtin.set_fact:
        monitoring_summary:
          cpu:    "{{ cpu_used | default('n/a') }}"
          memory: "{{ memory_used | default('n/a') }}"
          disk:   "{{ disk_used_max | default('n/a') }}"
          k3s:    "{{ k3s_storage_gb | default('n/a') }}"
          failed: "{{ (cpu_fail | default(false)) or (memory_fail | default(false)) or (disk_fail | default(false)) or (k3s_fail | default(false)) }}"

- name: Reporting & final decision (controller only)
  hosts: localhost
  connection: local
  gather_facts: no
  run_once: true
  tasks:

    - name: Show cluster resource overview
      ansible.builtin.debug:
        msg: |
          ## Cluster Resource Summary

          | Host                  | CPU % | Mem % | Disk % | k3s GB | Status |
          |-----------------------|-------|-------|--------|--------|--------|
          {% for host in groups['all'] | sort %}
          | {{ host | truncate(21) }} | {{ hostvars[host].monitoring_summary.cpu | default('err') }} | {{ hostvars[host].monitoring_summary.memory | default('err') }} | {{ hostvars[host].monitoring_summary.disk | default('err') }} | {{ hostvars[host].monitoring_summary.k3s | default('err') }} | {{ 'FAIL' if hostvars[host].monitoring_summary.failed else 'OK' }} |
          {% endfor %}

    - name: Show detailed filesystem usage
      ansible.builtin.debug:
        msg: |
          ## Filesystem Usage Details

          {% for host in groups['all'] | sort %}
          ### {{ host }}

          | Mount                     | Usage  |
          |---------------------------|--------|
          {% for fs in hostvars[host].filesystems | default([]) %}
          | {{ fs.mount | truncate(25) }} | {{ fs.usage }} |
          {% endfor %}
          {% if not hostvars[host].filesystems | default([]) %}| (no filesystem data)     | —      |{% endif %}

          {% endfor %}

    - name: Build list of failed hosts
      ansible.builtin.set_fact:
        failed_hosts: "{{ groups['all'] | select('ansible_hostvar', 'monitoring_summary.failed', true) | list }}"

    - name: FAIL the job if any node is over threshold
      ansible.builtin.fail:
        msg: |
          🚨 Resource thresholds exceeded on:

          {{ failed_hosts | join('\n  • ') | default('— none —') }}
      when: failed_hosts | length > 0
