---
- name: AWX-safe node resource monitoring
  hosts: all
  become: yes
  gather_facts: no

  vars:
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 80
    k3s_storage_threshold_gb: 10

  tasks:

    ######################
    # CPU
    ######################

    - name: Get CPU usage
      shell: top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}'
      register: cpu_raw
      changed_when: false

    - name: Normalize CPU
      set_fact:
        cpu_used: "{{ cpu_raw.stdout | float }}"
        cpu_fail: "{{ (cpu_raw.stdout | float) > cpu_threshold }}"


    ######################
    # MEMORY
    ######################

    - name: Get memory usage
      shell: free | awk '/Mem:/ { print ($3/$2)*100 }'
      register: mem_raw
      changed_when: false

    - name: Normalize memory
      set_fact:
        memory_used: "{{ mem_raw.stdout | float }}"
        memory_fail: "{{ (mem_raw.stdout | float) > memory_threshold }}"


    ######################
    # FILESYSTEMS
    ######################

    - name: Get filesystem usage
      shell: >
        df -hP --output=target,pcent
        -x tmpfs -x devtmpfs -x overlay -x squashfs
        | tail -n +2
      register: fs_raw
      changed_when: false

    - name: Initialize filesystem facts
      set_fact:
        filesystems: []
        disk_used_max: 0

    - name: Parse filesystem usage safely
      set_fact:
        filesystems: "{{ filesystems + [ { 'mount': fs_parts[0], 'usage': fs_parts[1] } ] }}"
        disk_used_max: >-
          {{
            fs_percent > disk_used_max
            | ternary(fs_percent, disk_used_max)
          }}
      vars:
        fs_parts: "{{ item.split() }}"
        fs_percent: "{{ item.split()[1] | regex_replace('%','') | int }}"
      loop: "{{ fs_raw.stdout_lines }}"

    - name: Evaluate disk status
      set_fact:
        disk_fail: "{{ disk_used_max > disk_threshold }}"


    ######################
    # K3s STORAGE
    ######################

    - name: Get K3s containerd storage usage (GB)
      shell: >
        du -s --block-size=1G /var/lib/rancher/k3s/agent/containerd
        2>/dev/null | awk '{print $1}' || echo 0
      register: k3s_raw
      changed_when: false

    - name: Normalize K3s storage
      set_fact:
        k3s_storage_gb: "{{ k3s_raw.stdout | int }}"
        k3s_fail: "{{ (k3s_raw.stdout | int) > k3s_storage_threshold_gb }}"


    ######################
    # HOST SUMMARY
    ######################

    - name: Build host monitoring summary
      set_fact:
        monitoring_summary:
          cpu: "{{ '%.1f' | format(cpu_used) }}"
          memory: "{{ '%.1f' | format(memory_used) }}"
          disk: "{{ disk_used_max }}"
          k3s: "{{ k3s_storage_gb }}"
          failed: "{{ cpu_fail or memory_fail or disk_fail or k3s_fail }}"


    ######################
    # CONSOLIDATED REPORTS
    ######################

    - name: Print cluster resource summary
      run_once: true
      delegate_to: localhost
      debug:
        msg: |
          ## 📊 Cluster Resource Summary

          | Host | CPU % | MEM % | Max Disk % | K3s GB | Status |
          |------|-------|-------|------------|--------|--------|
          {% for h in groups['all'] %}
          | {{ h }} | {{ hostvars[h].monitoring_summary.cpu }} | {{ hostvars[h].monitoring_summary.memory }} | {{ hostvars[h].monitoring_summary.disk }} | {{ hostvars[h].monitoring_summary.k3s }} | {{ 'FAIL' if hostvars[h].monitoring_summary.failed else 'OK' }} |
          {% endfor %}

    - name: Print filesystem usage per host
      run_once: true
      delegate_to: localhost
      debug:
        msg: |
          ## 💽 Filesystem Usage

          {% for h in groups['all'] %}
          ### {{ h }}

          | Mount | Usage |
          |-------|-------|
          {% for fs in hostvars[h].filesystems %}
          | {{ fs.mount }} | {{ fs.usage }} |
          {% endfor %}

          {% endfor %}


    ######################
    # FINAL FAIL (ONLY HERE)
    ######################

    - name: Initialize failed hosts list
      run_once: true
      delegate_to: localhost
      set_fact:
        failed_hosts: []

    - name: Collect failed hosts
      run_once: true
      delegate_to: localhost
      set_fact:
        failed_hosts: "{{ failed_hosts + [item] }}"
      loop: "{{ groups['all'] }}"
      when: hostvars[item].monitoring_summary.failed

    - name: Fail if any host exceeded thresholds
      run_once: true
      delegate_to: localhost
      fail:
        msg: |
          🚨 Resource thresholds exceeded on the following hosts:

          {{ failed_hosts | join(', ') }}
      when: failed_hosts | length > 0
