---
- name: AWX-safe node resource monitoring - prepare controller
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Mark controller for reporting
      ansible.builtin.set_fact:
        monitoring_controller: true
      run_once: true

- name: Collect resource metrics on all nodes
  hosts: all
  become: yes
  gather_facts: false

  vars:
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 80
    k3s_storage_threshold_gb: 10

  tasks:
    - name: Get CPU usage (100 - idle %)
      ansible.builtin.shell: >
        top -bn1 | grep -i "cpu(s)" | awk '{print 100 - $8}'
      register: cpu_raw
      changed_when: false
      check_mode: false

    - name: Set CPU facts
      ansible.builtin.set_fact:
        cpu_used: "{{ cpu_raw.stdout | float | round(1) }}"
        cpu_fail: "{{ (cpu_raw.stdout | float) > cpu_threshold }}"

    - name: Get memory usage percentage
      ansible.builtin.shell: >
        free | awk '/^Mem:/ {printf "%.1f", ($3/$2)*100}'
      register: mem_raw
      changed_when: false
      check_mode: false

    - name: Set memory facts
      ansible.builtin.set_fact:
        memory_used: "{{ mem_raw.stdout | float }}"
        memory_fail: "{{ (mem_raw.stdout | float) > memory_threshold }}"

    - name: Get filesystem usage (excluding loop/tmpfs)
      ansible.builtin.shell: >
        df -hP | awk 'NR>1 && $1 !~ /^(tmpfs|devtmpfs|overlay)$/ && $NF !~ /^\/dev\/loop/ {print $NF " " $5}'
      register: fs_raw
      changed_when: false
      check_mode: false

    - name: Calculate max disk usage and fail flag
      ansible.builtin.set_fact:
        disk_used_max: >-
          {{ fs_raw.stdout_lines
             | map('split')
             | map('last')
             | map('regex_replace', '%', '')
             | map('int')
             | max(default=0) }}
        disk_fail: >-
          {{ (fs_raw.stdout_lines
              | map('split')
              | map('last')
              | map('regex_replace', '%', '')
              | map('int')
              | max(default=0)) > disk_threshold }}

    - name: Build filesystem list for report
      ansible.builtin.set_fact:
        filesystems: >-
          {{ fs_raw.stdout_lines
             | map('split', ' ', 1)
             | map('zip', ['mount', 'usage'])
             | map('community.general.dict_kv') }}

    - name: Get k3s containerd storage (GB) - ignore if missing
      ansible.builtin.shell: >
        du -sx --block-size=1G /var/lib/rancher/k3s/agent/containerd 2>/dev/null | cut -f1 || echo 0
      register: k3s_raw
      changed_when: false
      check_mode: false
      ignore_errors: true

    - name: Set k3s facts
      ansible.builtin.set_fact:
        k3s_storage_gb: "{{ k3s_raw.stdout | int }}"
        k3s_fail: "{{ (k3s_raw.stdout | int) > k3s_storage_threshold_gb }}"

    - name: Build host monitoring summary
      ansible.builtin.set_fact:
        monitoring_summary:
          cpu: "{{ cpu_used | default('n/a') }}"
          memory: "{{ memory_used | default('n/a') }}"
          disk: "{{ disk_used_max | default('n/a') }}"
          k3s: "{{ k3s_storage_gb | default('n/a') }}"
          failed: "{{ cpu_fail | default(false) or memory_fail | default(false) or disk_fail | default(false) or k3s_fail | default(false) }}"

- name: Generate reports and fail if needed (controller only)
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  tasks:
    - name: Display cluster resource summary
      ansible.builtin.debug:
        msg: |
          ## Cluster Resource Summary

          | Host                  | CPU % | Mem % | Disk % | k3s GB | Status |
          |-----------------------|-------|-------|--------|--------|--------|
          {% for h in groups.all | sort %}
          | {{ h | truncate(21) }} | {{ hostvars[h].monitoring_summary.cpu | default('err') }} | {{ hostvars[h].monitoring_summary.memory | default('err') }} | {{ hostvars[h].monitoring_summary.disk | default('err') }} | {{ hostvars[h].monitoring_summary.k3s | default('err') }} | {{ 'FAIL' if hostvars[h].monitoring_summary.failed else 'OK' }} |
          {% endfor %}

    - name: Display detailed filesystem usage
      ansible.builtin.debug:
        msg: |
          ## Filesystem Usage per Host

          {% for h in groups.all | sort %}
          ### {{ h }}

          | Mount Point              | Usage  |
          |--------------------------|--------|
          {% for fs in hostvars[h].filesystems | default([]) %}
          | {{ fs.mount | truncate(24) }} | {{ fs.usage }} |
          {% else %}
          | (no data)                | —      |
          {% endfor %}

          {% endfor %}

    - name: Collect failed hosts
      ansible.builtin.set_fact:
        failed_hosts: "{{ groups.all | select('hostvar_defined', 'monitoring_summary.failed') | select('equalto', true, 'monitoring_summary.failed') | list }}"

    - name: Fail playbook if thresholds exceeded
      ansible.builtin.fail:
        msg: |
          🚨 CRITICAL: Resource thresholds exceeded on:

          • {{ failed_hosts | join('\n• ') | default('— none —') }}
      when: failed_hosts | length > 0
