---
- name: Monitor CPU, Memory, and Disk Usage on K3s Node
  hosts: all
  become: yes
  gather_facts: no

  vars:
    cpu_threshold: 80        # %
    memory_threshold: 80     # %
    disk_threshold: 80       # %
    k3s_storage_threshold_gb: 10  # Alert if containerd storage > this many GB

  tasks:

    ######################
    # CPU MONITORING
    ######################

    - name: Get CPU usage
      shell: |
        top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}'
      register: cpu_usage
      changed_when: false

    - name: Set CPU usage fact
      set_fact:
        cpu_used: "{{ cpu_usage.stdout | float }}"

    - name: Fail if CPU usage is high
      fail:
        msg: "CPU usage high: {{ cpu_used }}% (Threshold: {{ cpu_threshold }}%)"
      when: cpu_used | float > cpu_threshold


    ######################
    # MEMORY MONITORING
    ######################

    - name: Get memory usage
      shell: |
        free | awk '/Mem:/ { printf("%.2f"), $3/$2 * 100 }'
      register: memory_usage
      changed_when: false

    - name: Set memory usage fact
      set_fact:
        memory_used: "{{ memory_usage.stdout | float }}"

    - name: Fail if memory usage is high
      fail:
        msg: "Memory usage high: {{ memory_used }}% (Threshold: {{ memory_threshold }}%)"
      when: memory_used | float > memory_threshold


    ######################
    # DISK MONITORING (Host Filesystems Only)
    ######################

    - name: Get disk usage (exclude tmpfs, devtmpfs, overlay, and K3s containerd paths)
      shell: |
        df -h --output=pcent,target -x tmpfs -x devtmpfs -x overlay \
          | grep -vE '/run/k3s|/containerd/runtime.v2.task' \
          | tail -n +2
      register: disk_usage
      changed_when: false
      failed_when: disk_usage.rc != 0 and 'No such file' not in disk_usage.stderr  # Tolerate empty output

    - name: Check disk usage thresholds on host filesystems
      fail:
        msg: "Disk usage high on {{ item.split()[-1] }}: {{ item.split()[0] }} (Threshold: {{ disk_threshold }}%)"
      loop: "{{ disk_usage.stdout_lines | default([]) }}"
      when: disk_usage.stdout_lines | default([]) | length > 0 and (item.split()[0].rstrip('%') | int > disk_threshold)


    ######################
    # K3s Containerd Storage Check (Optional - Real Heavy User)
    ######################

    - name: Get K3s containerd storage usage
      shell: |
        du -sh /var/lib/rancher/k3s/agent/containerd 2>/dev/null | awk '{print $1}' || echo "0K"
      register: k3s_storage
      changed_when: false

    - name: Convert K3s storage to GB for comparison
      set_fact:
        k3s_storage_gb: >-
          {{ 
            (k3s_storage.stdout | regex_replace('Gi?B?', '')) | float if 'G' in k3s_storage.stdout else
            (k3s_storage.stdout | regex_replace('Mi?B?', '')) | float / 1024 if 'M' in k3s_storage.stdout else 0
          }}

    - name: Fail if K3s containerd storage is excessively high
      fail:
        msg: "K3s containerd storage high: {{ k3s_storage.stdout }} (~{{ k3s_storage_gb | round(1) }} GB) - Check images, snapshots, logs (Threshold: {{ k3s_storage_threshold_gb }} GB)"
      when: k3s_storage_gb > k3s_storage_threshold_gb
