---
- name: Monitor CPU, Memory, Disk, and K3s Storage on Nodes
  hosts: all
  become: yes
  gather_facts: no

  vars:
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 80
    k3s_storage_threshold_gb: 10

  tasks:

    ######################
    # CPU MONITORING
    ######################

    - name: Get CPU usage
      shell: |
        top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}'
      register: cpu_usage
      changed_when: false

    - name: Set CPU usage fact
      set_fact:
        cpu_used: "{{ cpu_usage.stdout | float }}"

    - name: Fail if CPU usage is high
      fail:
        msg: "CPU usage high: {{ cpu_used | float | round(1) }}% (Threshold: {{ cpu_threshold }}%)"
      when: (cpu_used | float) > (cpu_threshold | float)


    ######################
    # MEMORY MONITORING
    ######################

    - name: Get memory usage
      shell: |
        free | awk '/Mem:/ { printf("%.2f"), $3/$2 * 100 }'
      register: memory_usage
      changed_when: false

    - name: Set memory usage fact
      set_fact:
        memory_used: "{{ memory_usage.stdout | float }}"

    - name: Fail if memory usage is high
      fail:
        msg: "Memory usage high: {{ memory_used | float | round(1) }}% (Threshold: {{ memory_threshold }}%)"
      when: (memory_used | float) > (memory_threshold | float)


    ######################
    # DISK MONITORING
    ######################

    - name: Get disk usage (host filesystems only)
      shell: |
        df -h --output=pcent,target -x tmpfs -x devtmpfs -x overlay -x squashfs \
        | grep -vE '/run/k3s|/containerd/runtime.v2.task' \
        | tail -n +2
      register: disk_usage
      changed_when: false

    - name: Parse disk usage percentages
      set_fact:
        disk_usage_list: >-
          {{
            disk_usage.stdout_lines
            | map('regex_replace', '%', '')
            | map('split')
            | map('first')
            | map('int')
            | list
          }}

    - name: Determine highest disk usage %
      set_fact:
        disk_used_max: "{{ disk_usage_list | max }}"
      when: disk_usage_list | length > 0

    - name: Default disk usage to 0 when no disks found
      set_fact:
        disk_used_max: 0
      when: disk_usage_list | length == 0

    - name: Fail if disk usage is high
      fail:
        msg: "Disk usage high: {{ disk_used_max }}% (Threshold: {{ disk_threshold }}%)"
      when: (disk_used_max | int) > (disk_threshold | int)


    ######################
    # K3s CONTAINERD STORAGE
    ######################

    - name: Get K3s containerd storage usage in GB
      shell: |
        du -s --block-size=1G /var/lib/rancher/k3s/agent/containerd 2>/dev/null | awk '{print $1}' || echo 0
      register: k3s_storage_gb_raw
      changed_when: false

    - name: Set K3s storage fact
      set_fact:
        k3s_storage_gb: "{{ k3s_storage_gb_raw.stdout | int }}"

    - name: Fail if K3s storage is high
      fail:
        msg: "K3s containerd storage high: {{ k3s_storage_gb }} GB (Threshold: {{ k3s_storage_threshold_gb }} GB)"
      when: (k3s_storage_gb | int) > (k3s_storage_threshold_gb | int)


    ######################
    # SAVE PER-HOST SUMMARY (FACT)
    ######################

    - name: Save host monitoring summary
      set_fact:
        monitoring_summary:
          cpu: "{{ cpu_used | float | round(1) }}"
          memory: "{{ memory_used | float | round(1) }}"
          disk: "{{ disk_used_max }}"
          k3s: "{{ k3s_storage_gb }}"


    ######################
    # CONSOLIDATED REPORT
    ######################

    - name: Display consolidated resource usage table
      run_once: true
      delegate_to: localhost
      debug:
        msg: |
          ======================================================
          K3s Cluster Resource Usage Summary
          ======================================================
          Hostname              CPU%    MEM%    DISK%   K3s(GB)
          ------------------------------------------------------
          {% for host in groups['all'] %}
          {{ "%-20s" | format(host) }}
          {{ "%-7s" | format(hostvars[host].monitoring_summary.cpu) }}
          {{ "%-7s" | format(hostvars[host].monitoring_summary.memory) }}
          {{ "%-7s" | format(hostvars[host].monitoring_summary.disk) }}
          {{ "%-7s" | format(hostvars[host].monitoring_summary.k3s) }}
          {% endfor %}
          ======================================================
