---
- name: AWX-safe node resource monitoring - prepare controller
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Mark controller for reporting
      ansible.builtin.set_fact:
        is_monitoring_controller: true
      run_once: true

- name: Collect resource metrics on all nodes
  hosts: all
  become: true
  gather_facts: false
  vars:
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 80
    k3s_storage_threshold_gb: 10
  tasks:
    - name: Get CPU usage (100 - idle %)
      ansible.builtin.shell: >-
        top -bn1 | grep -i "cpu(s)" | awk '{print 100 - $8}'
      register: cpu_raw
      changed_when: false
      check_mode: false

    - name: Set CPU facts
      ansible.builtin.set_fact:
        cpu_used_pct: "{{ cpu_raw.stdout | float | default(0) }}"
        cpu_over_threshold: "{{ (cpu_raw.stdout | float | default(0)) > cpu_threshold }}"

    - name: Get memory usage percentage
      ansible.builtin.shell: >-
        free | awk '/^Mem:/ {printf "%.1f", ($3/$2)*100}'
      register: mem_raw
      changed_when: false
      check_mode: false

    - name: Set memory facts
      ansible.builtin.set_fact:
        memory_used_pct: "{{ mem_raw.stdout | float | default(0) }}"
        memory_over_threshold: "{{ (mem_raw.stdout | float | default(0)) > memory_threshold }}"

    - name: Get filesystem usage (skip tmpfs/loop/overlay)
      ansible.builtin.shell: >-
        df -hP | awk 'NR>1 && $1 !~ /^(tmpfs|devtmpfs|overlay)$/ && $NF !~ /^\/dev\/loop/ {print $NF " " $5}'
      register: fs_raw
      changed_when: false
      check_mode: false

    - name: Calculate max disk usage and fail flag
      ansible.builtin.set_fact:
        disk_percentages: >-
          {{ fs_raw.stdout_lines
             | map('split')
             | map('last')
             | map('regex_replace', '%', '')
             | map('int') | list }}
        disk_used_max_pct: >-
          {{ disk_percentages | max(default=0) }}
        disk_over_threshold: >-
          {{ disk_percentages | length > 0 and (disk_percentages | max) > disk_threshold }}

    - name: Build filesystem list for report
      ansible.builtin.set_fact:
        filesystem_usage: >-
          {{ fs_raw.stdout_lines
             | map('split', ' ', 1)
             | map('community.general.dict_kv', keys=['mount','usage']) | list }}

    - name: Get k3s containerd storage usage (GB) - safe if missing
      ansible.builtin.shell: >-
        du -sx --block-size=1G /var/lib/rancher/k3s/agent/containerd 2>/dev/null | cut -f1 || echo 0
      register: k3s_raw
      changed_when: false
      check_mode: false
      ignore_errors: true

    - name: Set k3s facts
      ansible.builtin.set_fact:
        k3s_storage_gb: "{{ k3s_raw.stdout | int | default(0) }}"
        k3s_over_threshold: "{{ (k3s_raw.stdout | int | default(0)) > k3s_storage_threshold_gb }}"

    - name: Build host monitoring summary
      ansible.builtin.set_fact:
        monitoring_summary:
          cpu: "{{ cpu_used_pct }}"
          memory: "{{ memory_used_pct }}"
          disk: "{{ disk_used_max_pct }}"
          k3s: "{{ k3s_storage_gb }}"
          failed: "{{ cpu_over_threshold or memory_over_threshold or disk_over_threshold or k3s_over_threshold }}"

- name: Generate reports and fail if needed (controller only)
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  tasks:
    - name: Display cluster resource summary
      ansible.builtin.debug:
        msg: |
          ## Cluster Resource Summary

          | Host                  | CPU % | Mem % | Disk % | k3s GB | Status |
          |:----------------------|------:|------:|-------:|-------:|--------|
          {% for host in groups['all'] | sort %}
          | {{ host | truncate(21) }} | {{ hostvars[host].monitoring_summary.cpu | default('n/a') }} | {{ hostvars[host].monitoring_summary.memory | default('n/a') }} | {{ hostvars[host].monitoring_summary.disk | default('n/a') }} | {{ hostvars[host].monitoring_summary.k3s | default('n/a') }} | {{ 'FAIL' if hostvars[host].monitoring_summary.failed | default(false) else 'OK' }} |
          {% endfor %}

    - name: Display detailed filesystem usage
      ansible.builtin.debug:
        msg: |
          ## Filesystem Usage per Host

          {% for host in groups['all'] | sort %}
          ### {{ host }}
          | Mount Point              | Usage  |
          |:-------------------------|-------:|
          {% for fs in hostvars[host].filesystem_usage | default([]) %}
          | {{ fs.mount | truncate(24) }} | {{ fs.usage }} |
          {% else %}
          | (no data collected)      | —      |
          {% endfor %}

          {% endfor %}

    - name: Collect failed hosts (robust against missing facts)
      ansible.builtin.set_fact:
        failed_hosts: >-
          {{ groups['all']
             | select('defined', hostvars[ item ].get('monitoring_summary', {}))
             | selectattr('monitoring_summary.failed', 'equalto', true)
             | list }}

    - name: Fail the playbook if any node exceeds thresholds
      ansible.builtin.fail:
        msg: |
          🚨 Resource thresholds exceeded on the following nodes:

          • {{ failed_hosts | join('\n• ') | default('none') }}
      when: failed_hosts | length > 0
