---
- name: Monitor CPU, Memory, Disk, and K3s Storage on Nodes
  hosts: all
  become: yes
  gather_facts: no

  vars:
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 80
    k3s_storage_threshold_gb: 10

  tasks:

    ######################
    # CPU MONITORING
    ######################

    - name: Get CPU usage
      shell: "top -bn1 | awk '/Cpu\\(s\\)/ {print 100 - $8}'"
      register: cpu_raw
      changed_when: false

    - name: Set CPU usage fact
      set_fact:
        cpu_used: "{{ cpu_raw.stdout | float }}"

    ######################
    # MEMORY MONITORING
    ######################

    - name: Get memory usage
      shell: "free | awk '/Mem:/ {print ($3/$2)*100}'"
      register: mem_raw
      changed_when: false

    - name: Set memory usage fact
      set_fact:
        memory_used: "{{ mem_raw.stdout | float }}"

    ######################
    # DISK MONITORING
    ######################

    - name: Get max disk usage %
      shell: |
        df -P --output=pcent -x tmpfs -x devtmpfs \
        | tail -n +2 | tr -d '%' | sort -n | tail -1
      register: disk_raw
      changed_when: false

    - name: Set disk usage fact
      set_fact:
        disk_used: "{{ disk_raw.stdout | default('0') | int }}"

    ######################
    # K3s STORAGE
    ######################

    - name: Get K3s containerd storage usage (GB)
      shell: "du -s --block-size=1G /var/lib/rancher/k3s/agent/containerd 2>/dev/null | awk '{print $1}' || echo 0"
      register: k3s_raw
      changed_when: false

    - name: Set K3s storage fact
      set_fact:
        k3s_storage_gb: "{{ k3s_raw.stdout | int }}"

    ######################
    # STATUS EVALUATION (FIXED)
    ######################

    - name: Determine host status
      set_fact:
        host_status: >-
          {{
            'FAIL'
            if (cpu_used | float) > (cpu_threshold | float)
            or (memory_used | float) > (memory_threshold | float)
            or (disk_used | int) > (disk_threshold | int)
            or (k3s_storage_gb | int) > (k3s_storage_threshold_gb | int)
            else 'OK'
          }}

    ######################
    # SAVE PER-HOST SUMMARY
    ######################

    - name: Save host monitoring summary
      set_fact:
        monitoring_summary:
          cpu: "{{ '%.1f' | format(cpu_used | float) }}"
          memory: "{{ '%.1f' | format(memory_used | float) }}"
          disk: "{{ disk_used | int }}"
          k3s: "{{ k3s_storage_gb | int }}"
          status: "{{ host_status }}"

    ######################
    # CONSOLIDATED REPORT
    ######################

    - name: Build consolidated resource usage table
      run_once: true
      delegate_to: localhost
      set_fact:
        consolidated_report: |
          ============================================================
          📊 K3s Cluster Resource Usage Summary
          ============================================================
          Hostname                              CPU%   MEM%   DISK%   K3sGB   Status
          ------------------------------------------------------------
          {% for host in groups['all'] %}
          {{ "%-36s %5s %6s %7s %7s   %s"
             | format(
                 host,
                 hostvars[host].monitoring_summary.cpu,
                 hostvars[host].monitoring_summary.memory,
                 hostvars[host].monitoring_summary.disk,
                 hostvars[host].monitoring_summary.k3s,
                 hostvars[host].monitoring_summary.status
               )
          }}
          {% endfor %}
          ============================================================

    - name: Display consolidated resource usage table
      run_once: true
      delegate_to: localhost
      debug:
        msg: "{{ consolidated_report }}"

    ######################
    # FAIL PLAY IF ANY HOST FAILED
    ######################

    - name: Fail play if any host exceeded thresholds
      run_once: true
      delegate_to: localhost
      fail:
        msg: "One or more hosts exceeded resource thresholds. See consolidated report above."
      when: >
        groups['all']
        | map('extract', hostvars, 'monitoring_summary')
        | selectattr('status', 'equalto', 'FAIL')
        | list
        | length > 0
