
    - name: Get k3s containerd storage usage safely
      ansible.builtin.shell: "du -sx --block-size=1G /var/lib/rancher/k3s/agent/containerd 2>/dev/null | cut -f1 || echo 0"
      register: k3s_raw
      ignore_errors: true
      changed_when: false
      check_mode: false

    - name: Set k3s facts
      ansible.builtin.set_fact:
        k3s_storage_gb: "{{ k3s_raw.stdout | int | default(0) }}"
        k3s_over_threshold: "{{ (k3s_raw.stdout | int | default(0)) > k3s_storage_threshold_gb }}"

    - name: Build host monitoring summary
      ansible.builtin.set_fact:
        monitoring_summary:
          cpu: "{{ cpu_used_pct }}"
          memory: "{{ memory_used_pct }}"
          disk: "{{ disk_used_max_pct }}"
          k3s: "{{ k3s_storage_gb }}"
          failed: "{{ cpu_over_threshold or memory_over_threshold or disk_over_threshold or k3s_over_threshold }}"

- name: Generate reports and fail if needed (controller only)
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  tasks:
    - name: Display cluster resource summary
      ansible.builtin.debug:
        msg: |
          ## Cluster Resource Summary

          | Host                  | CPU % | Mem % | Disk % | k3s GB | Status |
          |:----------------------|------:|------:|-------:|-------:|--------|
          {% for host in groups['all'] | sort %}
          | {{ host | truncate(21) }} | {{ hostvars[host].monitoring_summary.cpu | default('n/a') }} | {{ hostvars[host].monitoring_summary.memory | default('n/a') }} | {{ hostvars[host].monitoring_summary.disk | default('n/a') }} | {{ hostvars[host].monitoring_summary.k3s | default('n/a') }} | {{ 'FAIL' if hostvars[host].monitoring_summary.failed | default(false) else 'OK' }} |
          {% endfor %}

    - name: Display detailed filesystem usage
      ansible.builtin.debug:
        msg: |
          ## Filesystem Usage per Host

          {% for host in groups['all'] | sort %}
          ### {{ host }}
          | Mount Point              | Usage  |
          |:-------------------------|-------:|
          {% for fs in hostvars[host].filesystem_usage | default([]) %}
          | {{ fs.mount | truncate(24) }} | {{ fs.usage }} |
          {% else %}
          | (no data collected)      | —      |
          {% endfor %}
          {% endfor %}

    - name: Collect failed hosts
      ansible.builtin.set_fact:
        failed_hosts: >-
          {{ hostvars
             | dict2items
             | selectattr('value.monitoring_summary.failed', 'defined')
             | selectattr('value.monitoring_summary.failed', 'equalto', true)
             | map(attribute='key')
             | list }}

    - name: Fail the playbook if any node exceeds thresholds
      ansible.builtin.fail:
        msg: |
          🚨 Resource thresholds exceeded on the following nodes:

          • {{ failed_hosts | join('\n• ') | default('none') }}
      when: failed_hosts | length > 0
