---
- name: AWX-safe node resource monitoring - prepare controller
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Mark controller for reporting
      ansible.builtin.set_fact:
        is_monitoring_controller: true
      run_once: true

- name: Collect resource metrics on all nodes
  hosts: all
  become: true
  gather_facts: false
  vars:
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 80
    filesystem_threshold: 80
    k3s_storage_threshold_gb: 10
  tasks:
    - name: Get CPU usage safely
      ansible.builtin.shell: "top -bn1 | grep -i 'cpu(s)' | awk '{print 100 - $8}'"
      register: cpu_raw
      ignore_errors: true
      changed_when: false
      check_mode: false

    - name: Set CPU facts
      ansible.builtin.set_fact:
        cpu_used_pct: "{{ cpu_raw.stdout | float | default(0) }}"
        cpu_over_threshold: "{{ cpu_raw.stdout | float(default=0) > cpu_threshold }}"

    - name: Get memory usage safely
      ansible.builtin.shell: "free | awk '/^Mem:/ {printf \"%.1f\", ($3/$2)*100}'"
      register: mem_raw
      ignore_errors: true
      changed_when: false
      check_mode: false

    - name: Set memory facts
      ansible.builtin.set_fact:
        memory_used_pct: "{{ mem_raw.stdout | float | default(0) }}"
        memory_over_threshold: "{{ mem_raw.stdout | float(default=0) > memory_threshold }}"

    - name: Get filesystem usage safely
      ansible.builtin.shell: >
        df -hP | awk 'NR>1 && $1 !~ /^(tmpfs|devtmpfs|overlay)$/ && $NF !~ /^\/dev\/loop/ {print $NF " " $5}'
      register: fs_raw
      ignore_errors: true
      changed_when: false
      check_mode: false

    - name: Initialize filesystem_usage list
      ansible.builtin.set_fact:
        filesystem_usage: []

    - name: Append filesystem usage safely with threshold
      ansible.builtin.set_fact:
        filesystem_usage: "{{ filesystem_usage + [fs_entry] }}"
      vars:
        fs_parts: "{{ item.split() }}"
        fs_entry:
          mount: "{{ fs_parts[0] }}"
          usage: "{{ fs_parts[1] }}"
          usage_percent: "{{ (fs_parts[1].rstrip('%') | int) }}"
          over_threshold: "{{ (fs_parts[1].rstrip('%') | int) >= filesystem_threshold }}"
      loop: "{{ fs_raw.stdout_lines | default([]) }}"
      when: item.split() | length >= 2

    - name: Calculate max disk usage and fail flag
      ansible.builtin.set_fact:
        disk_percentages: >-
          {{ fs_raw.stdout_lines | default([])
             | map('split')
             | map('last')
             | map('regex_replace', '%', '')
             | map('int') | list }}
        disk_used_max_pct: "{{ disk_percentages | default([0]) | max }}"
        disk_over_threshold: "{{ (disk_percentages | default([0]) | max) > disk_threshold }}"

    - name: Get k3s containerd storage usage safely
      ansible.builtin.shell: "du -sx --block-size=1G /var/lib/rancher/k3s/agent/containerd 2>/dev/null | cut -f1 || echo 0"
      register: k3s_raw
      ignore_errors: true
      changed_when: false
      check_mode: false

    - name: Set k3s facts
      ansible.builtin.set_fact:
        k3s_storage_gb: "{{ k3s_raw.stdout | int | default(0) }}"
        k3s_over_threshold: "{{ (k3s_raw.stdout | int | default(0)) > k3s_storage_threshold_gb }}"

    - name: Build host monitoring summary
      ansible.builtin.set_fact:
        monitoring_summary:
          cpu: "{{ cpu_used_pct }}"
          memory: "{{ memory_used_pct }}"
          disk: "{{ disk_used_max_pct }}"
          k3s: "{{ k3s_storage_gb }}"
          failed: "{{ cpu_over_threshold or memory_over_threshold or disk_over_threshold or (filesystem_usage | selectattr('over_threshold') | list | length > 0) }}"

- name: Generate reports and fail if needed (controller only)
  hosts: localhost
  connection: local
  gather_facts: false
  run_once: true
  tasks:
    - name: Collect failed hosts
      ansible.builtin.set_fact:
        failed_hosts: >-
          {{ hostvars
             | dict2items
             | selectattr('value.monitoring_summary.failed', 'defined')
             | selectattr('value.monitoring_summary.failed', 'equalto', true)
             | map(attribute='key')
             | list }}

    - name: Build HTML email body
      ansible.builtin.set_fact:
        html_email: |
          Subject: 🚨 Filesystem Threshold Alert
          To: krishnakumar.subramanian@ibm.com
          MIME-Version: 1.0
          Content-Type: text/html; charset=UTF-8

          <html>
          <body>
            <h2 style="color:red;">Filesystem Threshold Alert</h2>
            <p>Filesystems exceeding <b>{{ hostvars[groups['all'][0]].filesystem_threshold | default(80) }}%</b>:</p>

            {% for host in groups['all'] %}
            {% set fs_list = hostvars[host].filesystem_usage | selectattr('over_threshold') | list %}
            {% if fs_list | length > 0 %}
            <h3>{{ host }}</h3>
            <ul>
              {% for fs in fs_list %}
              <li>{{ fs.mount }} — {{ fs.usage }}</li>
              {% endfor %}
            </ul>
            {% endif %}
            {% endfor %}
          </body>
          </html>

    - name: Send HTML email using msmtp
      ansible.builtin.shell: |
        msmtp -t <<'EOF'
        {{ html_email }}
        EOF
      when: failed_hosts | length > 0
      changed_when: false

    - name: Fail the playbook if any node exceeds thresholds
      ansible.builtin.fail:
        msg: |
          🚨 Resource thresholds exceeded on the following nodes:
          • {{ failed_hosts | join('\n• ') }}
      when: failed_hosts | length > 0
