---
- name: Monitor CPU, Memory, Disk, and K3s Storage on Nodes
  hosts: all
  become: yes
  gather_facts: no

  vars:
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 80
    k3s_storage_threshold_gb: 10

  tasks:

    ######################
    # CPU
    ######################

    - name: Get CPU usage
      shell: top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}'
      register: cpu_usage
      changed_when: false

    - name: Normalize CPU
      set_fact:
        cpu_used: "{{ cpu_usage.stdout | float }}"
        cpu_status: "{{ 'FAIL' if (cpu_usage.stdout | float) > cpu_threshold else 'OK' }}"


    ######################
    # MEMORY
    ######################

    - name: Get memory usage
      shell: free | awk '/Mem:/ { printf("%.2f"), $3/$2 * 100 }'
      register: memory_usage
      changed_when: false

    - name: Normalize memory
      set_fact:
        memory_used: "{{ memory_usage.stdout | float }}"
        memory_status: "{{ 'FAIL' if (memory_usage.stdout | float) > memory_threshold else 'OK' }}"


    ######################
    # DISK
    ######################

    - name: Get disk usage (host filesystems only)
      shell: |
        df -h --output=pcent -x tmpfs -x devtmpfs -x overlay -x squashfs \
        | tail -n +2 | tr -d '%'
      register: disk_usage
      changed_when: false

    - name: Normalize disk
      set_fact:
        disk_used_max: "{{ disk_usage.stdout_lines | map('int') | max | default(0) }}"
        disk_status: "{{ 'FAIL' if (disk_usage.stdout_lines | map('int') | max | default(0)) > disk_threshold else 'OK' }}"


    ######################
    # K3s STORAGE
    ######################

    - name: Get K3s containerd storage usage (GB)
      shell: du -s --block-size=1G /var/lib/rancher/k3s/agent/containerd 2>/dev/null | awk '{print $1}' || echo 0
      register: k3s_storage_raw
      changed_when: false

    - name: Normalize K3s storage
      set_fact:
        k3s_storage_gb: "{{ k3s_storage_raw.stdout | int }}"
        k3s_status: "{{ 'FAIL' if (k3s_storage_raw.stdout | int) > k3s_storage_threshold_gb else 'OK' }}"


    ######################
    # HOST SUMMARY
    ######################

    - name: Save host monitoring summary
      set_fact:
        monitoring_summary:
          cpu: "{{ '%.1f' | format(cpu_used | float) }}"
          memory: "{{ '%.1f' | format(memory_used | float) }}"
          disk: "{{ disk_used_max | int }}"
          k3s: "{{ k3s_storage_gb | int }}"
          status: >-
            {{
              'FAIL'
              if 'FAIL' in [cpu_status, memory_status, disk_status, k3s_status]
              else 'OK'
            }}


    ######################
    # CONSOLIDATED REPORT
    ######################

    - name: Display consolidated resource usage table
      run_once: true
      delegate_to: localhost
      debug:
        msg: |
          ============================================================
          📊 K3s Cluster Resource Usage Summary
          ============================================================
          Hostname                              CPU%   MEM%   DISK%   K3sGB   Status
          ------------------------------------------------------------
          {% for host in groups['all'] %}
          {{ "%-36s %5s %6s %7s %7s   %s"
             | format(
                 host,
                 hostvars[host].monitoring_summary.cpu,
                 hostvars[host].monitoring_summary.memory,
                 hostvars[host].monitoring_summary.disk,
                 hostvars[host].monitoring_summary.k3s,
                 hostvars[host].monitoring_summary.status
               )
          }}
          {% endfor %}
          ============================================================


    ######################
    # FINAL FAIL (AFTER REPORT)
    ######################

    - name: Initialize failed hosts list
      run_once: true
      delegate_to: localhost
      set_fact:
        failed_hosts: []

    - name: Collect failed hosts
      run_once: true
      delegate_to: localhost
      set_fact:
        failed_hosts: "{{ failed_hosts + [item] }}"
      loop: "{{ groups['all'] }}"
      when: hostvars[item].monitoring_summary.status == 'FAIL'

    - name: Fail play if any host exceeded thresholds
      run_once: true
      delegate_to: localhost
      fail:
        msg: |
          🚨 One or more hosts exceeded resource thresholds.
          Failed hosts: {{ failed_hosts | join(', ') }}
      when: failed_hosts | length > 0
