---
- name: Monitor CPU, Memory, Disk, and K3s Storage on Nodes
  hosts: all
  become: yes
  gather_facts: no

  vars:
    cpu_threshold: 80
    memory_threshold: 80
    disk_threshold: 80
    k3s_storage_threshold_gb: 10

  tasks:

    ######################
    # CPU
    ######################

    - name: Get CPU usage
      shell: top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}'
      register: cpu_usage
      changed_when: false

    - name: Normalize CPU
      set_fact:
        cpu_used: "{{ cpu_usage.stdout | float }}"
        cpu_status: "{{ '游댮 FAIL' if (cpu_usage.stdout | float) > cpu_threshold else '游릭 OK' }}"


    ######################
    # MEMORY
    ######################

    - name: Get memory usage
      shell: free | awk '/Mem:/ { printf("%.2f"), $3/$2 * 100 }'
      register: memory_usage
      changed_when: false

    - name: Normalize memory
      set_fact:
        memory_used: "{{ memory_usage.stdout | float }}"
        memory_status: "{{ '游댮 FAIL' if (memory_usage.stdout | float) > memory_threshold else '游릭 OK' }}"


    ######################
    # DISK
    ######################

    - name: Get disk usage (host filesystems only)
      shell: |
        df -h --output=pcent -x tmpfs -x devtmpfs -x overlay -x squashfs \
        | tail -n +2 | tr -d '%'
      register: disk_usage
      changed_when: false

    - name: Normalize disk
      set_fact:
        disk_used_max: "{{ disk_usage.stdout_lines | map('int') | max | default(0) }}"
        disk_status: "{{ '游댮 FAIL' if (disk_usage.stdout_lines | map('int') | max | default(0)) > disk_threshold else '游릭 OK' }}"


    ######################
    # K3s STORAGE
    ######################

    - name: Get K3s containerd storage usage (GB)
      shell: du -s --block-size=1G /var/lib/rancher/k3s/agent/containerd 2>/dev/null | awk '{print $1}' || echo 0
      register: k3s_storage_raw
      changed_when: false

    - name: Normalize K3s storage
      set_fact:
        k3s_storage_gb: "{{ k3s_storage_raw.stdout | int }}"
        k3s_status: "{{ '游댮 FAIL' if (k3s_storage_raw.stdout | int) > k3s_storage_threshold_gb else '游릭 OK' }}"


    ######################
    # HOST SUMMARY (NO round())
    ######################

    - name: Save host monitoring summary
      set_fact:
        monitoring_summary:
          cpu: "{{ '%.1f' | format(cpu_used | float) }}"
          memory: "{{ '%.1f' | format(memory_used | float) }}"
          disk: "{{ disk_used_max | int }}"
          k3s: "{{ k3s_storage_gb | int }}"
          status: >-
            {{
              '游댮 FAIL'
              if 'FAIL' in [cpu_status, memory_status, disk_status, k3s_status]
              else '游릭 OK'
            }}


    ######################
    # CONSOLIDATED REPORT
    ######################

    - name: Display consolidated resource usage table
      run_once: true
      delegate_to: localhost
      debug:
        msg: |
          ## 游늵 K3s Cluster Resource Usage Summary

          | Hostname | CPU % | MEM % | DISK % | K3s GB | Status |
          |----------|-------|-------|--------|--------|--------|
          {% for host in groups['all'] -%}
          | {{ host }} | {{ hostvars[host].monitoring_summary.cpu }} | {{ hostvars[host].monitoring_summary.memory }} | {{ hostvars[host].monitoring_summary.disk }} | {{ hostvars[host].monitoring_summary.k3s }} | {{ hostvars[host].monitoring_summary.status }} |
          {% endfor %}


    ######################
    # FINAL FAIL (AFTER REPORT)
    ######################

    - name: Fail play if any host exceeded thresholds
      run_once: true
      delegate_to: localhost
      fail:
        msg: "游뚿 One or more hosts exceeded resource thresholds. See summary table above."
      when: >
        groups['all']
        | select('extract', hostvars, 'monitoring_summary')
        | selectattr('status', 'equalto', '游댮 FAIL')
        | list
        | length > 0
