---
- name: AWX-safe node resource monitoring – target nodes
  hosts: all
  become: yes
  gather_facts: false

- name: Prepare controller facts
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Mark this as controller
      ansible.builtin.set_fact:
        monitoring_controller: true

    - name: Define thresholds
      ansible.builtin.set_fact:
        cpu_threshold: 80
        memory_threshold: 80
        disk_threshold: 80
        k3s_storage_threshold_gb: 10

- name: Collect resource metrics from all nodes
  hosts: all
  become: yes
  gather_facts: false
  tasks:

    # ─── CPU ───────────────────────────────────────────────
    - name: Get CPU usage (idle % inverted)
      ansible.builtin.shell: >-
        top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}'
      register: cpu_raw
      changed_when: false
      check_mode: false

    - name: Set CPU facts
      ansible.builtin.set_fact:
        cpu_used: "{{ cpu_raw.stdout | float | round(1) }}"
        cpu_fail: "{{ (cpu_raw.stdout | float) > cpu_threshold }}"

    # ─── MEMORY ────────────────────────────────────────────
    - name: Get memory usage percentage
      ansible.builtin.shell: >-
        free | awk '/Mem:/ {print ($3/$2)*100}'
      register: mem_raw
      changed_when: false
      check_mode: false

    - name: Set memory facts
      ansible.builtin.set_fact:
        memory_used: "{{ mem_raw.stdout | float | round(1) }}"
        memory_fail: "{{ (mem_raw.stdout | float) > memory_threshold }}"

    # ─── DISK (max usage across filesystems) ──────────────
    - name: Get filesystem usage
      ansible.builtin.shell: >-
        df -hP | awk 'NR>1 {print $6 " " $5}'
      register: fs_raw
      changed_when: false
      check_mode: false

    - name: Parse filesystems into list
      ansible.builtin.set_fact:
        filesystems: >-
          {{
            fs_raw.stdout_lines
            | map('split')
            | map('zip', ['mount', 'usage'])
            | map('community.general.dict_kv')
          }}

    - name: Find highest disk usage
      ansible.builtin.set_fact:
        disk_used_max: >-
          {{
            fs_raw.stdout_lines
            | map('split')
            | map('last')
            | map('regex_replace', '%', '')
            | map('int')
            | max
          }}
        disk_fail: >-
          {{
            (fs_raw.stdout_lines
             | map('split')
             | map('last')
             | map('regex_replace', '%', '')
             | map('int')
             | max) > disk_threshold
          }}

    # ─── K3s containerd storage ───────────────────────────
    - name: Get K3s containerd directory size in GB
      ansible.builtin.shell: >-
        du -s --block-size=1G /var/lib/rancher/k3s/agent/containerd 2>/dev/null
        | awk '{print $1}' || echo 0
      register: k3s_raw
      changed_when: false
      check_mode: false

    - name: Set K3s storage facts
      ansible.builtin.set_fact:
        k3s_storage_gb: "{{ k3s_raw.stdout | int }}"
        k3s_fail: "{{ (k3s_raw.stdout | int) > k3s_storage_threshold_gb }}"

    # ─── Summary per host ─────────────────────────────────
    - name: Build per-host monitoring summary
      ansible.builtin.set_fact:
        monitoring_summary:
          cpu: "{{ cpu_used }}"
          memory: "{{ memory_used }}"
          disk: "{{ disk_used_max | default(0) }}"
          k3s: "{{ k3s_storage_gb | default(0) }}"
          failed: "{{ cpu_fail | default(false) or memory_fail | default(false) or disk_fail | default(false) or k3s_fail | default(false) }}"

- name: Generate reports and final check – run on controller only
  hosts: localhost
  gather_facts: false
  run_once: true
  tasks:

    - name: Print cluster-wide resource summary table
      ansible.builtin.debug:
        msg: |
          ## 📊 Cluster Resource Summary

          | Host          | CPU % | MEM % | Max Disk % | K3s GB | Status |
          |---------------|-------|-------|------------|--------|--------|
          {% for h in groups['all'] | sort %}
          | {{ h | truncate(13) }} | {{ hostvars[h].monitoring_summary.cpu | default('n/a') }} | {{ hostvars[h].monitoring_summary.memory | default('n/a') }} | {{ hostvars[h].monitoring_summary.disk | default('n/a') }} | {{ hostvars[h].monitoring_summary.k3s | default('n/a') }} | {{ 'FAIL' if hostvars[h].monitoring_summary.failed | default(false) else 'OK' }} |
          {% endfor %}

    - name: Print detailed filesystem usage
      ansible.builtin.debug:
        msg: |
          ## 💽 Filesystem Usage per Host

          {% for h in groups['all'] | sort %}
          ### {{ h }}

          | Mount Point               | Usage  |
          |---------------------------|--------|
          {% for fs in hostvars[h].filesystems | default([]) %}
          | {{ fs.mount | truncate(25) }} | {{ fs.usage }} |
          {% else %}
          | (no data collected)       | —      |
          {% endfor %}

          {% endfor %}

    - name: Collect list of failed hosts
      ansible.builtin.set_fact:
        failed_hosts: >-
          {{
            groups['all']
            | select('defined', 'monitoring_summary.failed')
            | select('equalto', true)
            | list
          }}

    - name: Fail the playbook if any host exceeded thresholds
      ansible.builtin.fail:
        msg: |
          🚨 Resource thresholds exceeded on the following hosts:

          {{ failed_hosts | join(', ') | default('(none)') }}
      when: failed_hosts | length > 0
